services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/app
    environment:
      - AUTH_SECRET_KEY=a874c3c88f0021451e195c991ba15d55cce127bd5b1d13b20e6d85692310848e
      - ENV=DEV
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=invest
      - PRINT_LOG=False
      - PYTHONUNBUFFERED=1
      - SELENIUM_HUB_URL=http://host.docker.internal:4444
      - SELENIUM_HUB_TIMEOUT=300
    depends_on:
      - db
      - chromium
      - selenium-hub
    networks:
      - my_shared_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 5s
      timeout: 2s
      retries: 5
    depends_on:
      - selenium-hub
      - chromium
    networks:
      - my_shared_network

  chromium:
    image: seleniarm/node-chromium:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_VNC_PASSWORD=123456
      - SE_NODE_MAX_SESSIONS=5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4442"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - my_shared_network

  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - my_shared_network
  
networks:
  my_shared_network:
    driver: bridge

volumes:
  pgdata: