"""create table scraper tickers data

Revision ID: 5fd6c7bee617
Revises: 62a9e41c6008
Create Date: 2024-11-25 13:01:38.327676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd6c7bee617'
down_revision: Union[str, None] = '62a9e41c6008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('''
        CREATE TABLE invest."scraper_tickers_data" (
            "id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "scraper_run_ticker_id" BIGINT NOT NULL,
            "data" JSONB NOT NULL,
            PRIMARY KEY("id")
        );
               
        ALTER TABLE invest."scraper_tickers_data"
        ADD CONSTRAINT scraper_tickers_data_scraper_run_ticker_id_fkey
        FOREIGN KEY("scraper_run_ticker_id") 
        REFERENCES invest."scraper_runs_tickers"("id")
        ON UPDATE NO ACTION ON DELETE CASCADE;
    ''')


def downgrade() -> None:
    op.execute('''
        DROP TABLE invest."scraper_tickers_data";
    ''')
