"""create table tickers_types

Revision ID: 808481e6bc64
Revises: 857b9d73b9ca
Create Date: 2024-11-21 12:20:11.356959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808481e6bc64'
down_revision: Union[str, None] = '857b9d73b9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('''
        CREATE TABLE invest."tickers_types" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "name" VARCHAR(255) NOT NULL,
            PRIMARY KEY("id")
        );
    ''')


def downgrade() -> None:
    op.execute('''
        DROP TABLE invest."tickers_types";
    ''')