"""create table scrapper_runs_tickers

Revision ID: 857b9d73b9ca
Revises: 22a881493358
Create Date: 2024-11-21 12:13:53.468158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857b9d73b9ca'
down_revision: Union[str, None] = '22a881493358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.execute('''
        CREATE TABLE invest."scrapper_runs_tickers" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "scrapper_run_id" BIGINT NOT NULL,
            "ticker_id" BIGINT NOT NULL,
            "started_at" TIMESTAMPTZ NOT NULL,
            "ended_at" TIMESTAMPTZ,
            "exec_failed" BOOLEAN NULL DEFAULT false,
            "cause_exec_failed" TEXT,
            PRIMARY KEY("id")
        );
    ''')


def downgrade() -> None:
    op.execute('''
        DROP TABLE invest."scrapper_runs_tickers";
    ''')