"""create table tickers

Revision ID: a7c6180722d3
Revises: 808481e6bc64
Create Date: 2024-11-21 12:21:43.422941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c6180722d3'
down_revision: Union[str, None] = '808481e6bc64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('''
        CREATE TABLE invest."tickers" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "name" VARCHAR(255) NOT NULL,
            "ticker_type_id" BIGINT NOT NULL,
            PRIMARY KEY("id")
        );
    ''')

    op.execute('''
        INSERT INTO invest."tickers" ("name", "ticker_type_id") VALUES ('WEGE3', 1);
        INSERT INTO invest."tickers" ("name", "ticker_type_id") VALUES ('HFOF11', 2);
        INSERT INTO invest."tickers" ("name", "ticker_type_id") VALUES ('BCFF11', 2);
        INSERT INTO invest."tickers" ("name", "ticker_type_id") VALUES ('CPTS11', 2);
        INSERT INTO invest."tickers" ("name", "ticker_type_id") VALUES ('KNCR11', 2);
        INSERT INTO invest."tickers" ("name", "ticker_type_id") VALUES ('KNRI11', 2);
        INSERT INTO invest."tickers" ("name", "ticker_type_id") VALUES ('HGLG11', 2);
        INSERT INTO invest."tickers" ("name", "ticker_type_id") VALUES ('VISC11', 2);
        INSERT INTO invest."tickers" ("name", "ticker_type_id") VALUES ('FIIB11', 2);
    ''')

def downgrade() -> None:
    op.execute('''
        DROP TABLE invest."tickers";
    ''')
