"""create table users

Revision ID: e1fafcd21851
Revises: 5fd6c7bee617
Create Date: 2024-12-05 12:25:21.308064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fafcd21851'
down_revision: Union[str, None] = '5fd6c7bee617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    op.execute('''
        CREATE TABLE invest."users" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "username" VARCHAR(255) NOT NULL UNIQUE,
            "full_name" VARCHAR(255) NOT NULL,
            "email" VARCHAR(255) NOT NULL,
            "hashed_password" VARCHAR(255) NOT NULL,
            "disabled" BOOLEAN NOT NULL,
            PRIMARY KEY("id")
        );
               
        CREATE INDEX "users_index_username" ON invest."users" ("username");

        CREATE INDEX "users_index_email" ON invest."users" ("email");
               
        INSERT INTO invest.users
        (username, full_name, email, hashed_password, disabled)
        VALUES('lperazzini', 'Leonardo Perazzini', 'leonardoperazzini@gmail.com', '$2a$10$mgNap1Ftqt/dJ/aMHnyNSOV88kuCuiPcosKqoPHGIj5mYN/wQsQ1.', false);
    ''')


def downgrade() -> None:
    op.execute('''
        DROP TABLE invest."users";
    ''')
